title: "虚拟松林里的小屋"
author: "Ling"
description: "@Ling, IHEP, Beijing"
permalink: /:title/
lang: "zh-cn"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"


# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "topo_defects.pdf", title: "文集"}
  - {file: "README.md", title: "关于作者"}
 

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "liximeng@ihep.ac.cn"}
  - {title: Github, icon: github, url: "https://CallOfXimeng.github.io"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
